config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/new'

  get 'users/show'

  get 'users/edit'

  resources :users

  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit]

  def index
    @current_page = params.fetch(:page, 0).to_i
    posts = Post.limit(20)
                 .offset(20 * params[:page].to_i)
                 .order(params.fetch(:sort, :id))
    # WE HAVE TO USE THE CODE BELOW SO THE SORT METHOD CAN WORK
    @posts = Post.order(:url).page params[:page]
  end

  def show
  end

  # GET /users/new
  def new
    @post = Post.new
  end

  # GET /users/1/edit
  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:movie_title, :url, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @current_page = params.fetch(:page, 0).to_i
    @users = User.limit(20)
                 .offset(20 * params[:page].to_i)
                 .order(params.fetch(:sort, :id))
    @users = User.order(:profile_name).page params[:page]
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit

  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

# private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:profile_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMDLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/cosmo/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <p style='color: green;'><%= notice %></p>
      <p style='color: red;'><%= alert %></p>

      <nav>
        <%= link_to 'HOME', posts_path %> |
        <%= link_to 'NEW MOVIE', new_post_path %> |
        <%= link_to 'NEW USER', new_user_path %>
      </nav>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </div>
</div>

<br>

<!--  -->

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :movie_title %>
  </div>

  <div class="form-inputs">
    <%= f.input :url %>
  </div>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Movie Title</th>
      <th>URL</th>
      <th>Description</th>

      <!-- We can use the following code to sort by Profile Name: (sort: :profile_name) -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.movie_title %></td>
        <td><%= post.url %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<nav>
  <ul class='pagination'>
    <li class="<%= 'disabled' if @current_page <= 0 %>">
      <%= link_to('Previous', (posts_path(page: @current_page - 1) if @current_page > 0), :'aria-label' => 'Previous') %>
    </li>

    <% ((@current_page - 2)..(@current_page + 2)).each do |page_num| %>
      <% if page_num == @current_page %>
        <li class='active'>
          <% elsif page_num < 0 %>
        <li class="disabled">
         <% else %>
        <li>
        <% end %>

          <% if page_num < 0 %>
           <%= link_to('*', '#') %>
          <% else %>
           <%= link_to(page_num, posts_path(page: page_num)) %>
          <% end %>
        </li>
    <% end %>

    <li class="<%= 'disabled' if @posts.length > 0 %>">
     <%= link_to('Next >', (posts_path(page: @current_page + 1) if @posts.length > 0), :'aria-label' => 'Next')  %>
    </li>

  </ul>
</nav>

app/views/posts/new.html.erb
<h1>Enter Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie Title:</strong>
  <%= @post.movie_title %>
</p>

<p>
  <strong>URL:</strong>
  <%= @post.url %>
</p>


<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :profile_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<!DOCTYPE html>

<h1>Listing Users</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>ID</th>
      <th>URL</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.profile_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Profile name:</strong>
  <%= @user.profile_name %>
</p>

<%= link_to 'Back', users_path %>